### ISSUE TITLE
fix mod compatibility badge colors

### ISSUE THREAD

**Issue by made-by-traxam** [raftmodding/web-monorepo#23]

**Comment by Felix-Puetz** [comment]
@made-by-traxam whats wrong with them?

**Comment by made-by-traxam** [comment]
![image](https://user-images.githubusercontent.com/10695278/125677925-5a7d5427-0865-40e1-9eb7-32a9d6e9528e.png)

up-to-date badges should be green, red is used to mark out-of-date mods

**Comment by Felix-Puetz** [comment]
![image](https://user-images.githubusercontent.com/50131232/125931339-9cf224a7-651a-414e-8143-f2abbe6a70f7.png)
they seem to be alright on my system
