### ISSUE TITLE
Restrict API endpoints

### ISSUE THREAD

**Issue by made-by-traxam** [raftmodding/web-monorepo#32]
The following API endpoints need to be restricted before release:
* [x] do not publish likes in ` GET /api/rest/mods`, this (especially user email addresses!) is sensitive data
  * [x] likes are also leaked in the response of the `PUT /api/rest/mods/:id` endpoint
* [x] #58
  * [x] `excludeAttributes: ['deletion']` does not seem to fulfill it's purpose, maybe conflicting with `associations: true`?
  * [x] we shouldn't use `associations: true` in general since this could leak sensitive data very easily, for example when a new association is added to the code
* [x] `POST /api/rest/mods` should not allow empty values for `description` and `readme`
* [x] `POST /api/rest/mods/:modId/versions`:
  * [x] missing check for whether the `id` provided in the request body matches `modId`
  * [x] missing check for whether `version` is a slug
  * [x] missing check whether a min/max raft version is set
* [x] `PUT /api/rest/mods/:modId/:versionId`
  * [x] do not allow changing `downloadUrl`, `fileHashes` and `downloadCount`
* [x] `POST /api/rest/passwordResets`
  * [x] missing check whether `email` is an email address. If discord users enter `discord-<DISCORD_USER_ID>`, the system will attempt to send a mail to that string.
  * [x] if there already is a password reset for a given user, return `200` anyways (to avoid leaking info)
* `DELETE /api/rest/passwordResets/:token`: password strength is not validated --> see #61 
* [x] why does `GET /api/rest/raftVersions/:id` require admin priviledges? all info displayed there can be requested via `GET /api/rest/raftVersions` --> route is only used by admins
* [x] remove `associations: true` from the raft versions endpoint, this currently has no use but could leak data unintentionally if we add further associations in the future
* [x] remove the `/api/rest/scheduledModDeletions/:id` route, we only support "create" ops for this resource anyways
* [x] remove the `GET /api/rest/users` route, we do not want to publish a list of all users!
* [x] remove the `email` and `role` attributes as well as the `likedMods` association from `GET /api/rest/users/:username`, this is private data!

**Comment by Felix-Puetz** [comment]
@made-by-traxam where is this endpoint?

**Comment by made-by-traxam** [comment]
> @made-by-traxam where is this endpoint?

By 'user list route', I mean `GET /api/rest/users`
