### ISSUE TITLE
Discord notifications fail when they are too long

### ISSUE THREAD

**Issue by made-by-traxam** [raftmodding/web-monorepo#65]
see https://discord.com/developers/docs/resources/channel#embed-object-embed-limits

**Comment by Felix-Staud** [comment]
just curious:
Where are producing discord notifications here? 
The project is not even online, or am I missing something?

**Comment by TeKGameR950** [comment]
> just curious: Where are producing discord notifications here? The project is not even online, or am I missing something?

https://github.com/raftmodding/discord-notification-service
https://github.com/raftmodding/discord-notification-client

**Comment by Felix-Staud** [comment]
@TeKGameR950 I see, so not directly related to the "new" website. Thanks for the info

**Comment by TeKGameR950** [comment]
Yeah, the issue is already present on the current site :'( So sometimes mod updates aren't shown which sucks.

**Comment by made-by-traxam** [comment]
In this new version, discord notifications are part of this repository. The bug also exists in the new codebase, there is no trimming feature implemented here
